/*
 * Gitea API
 *
 * This documentation describes the Gitea API.
 *
 * The version of the OpenAPI document: 1.22.0+dev-892-g9de5e39e2
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Activity {
    #[serde(rename = "act_user", skip_serializing_if = "Option::is_none")]
    pub act_user: Option<Box<models::User>>,
    #[serde(rename = "act_user_id", skip_serializing_if = "Option::is_none")]
    pub act_user_id: Option<i64>,
    #[serde(rename = "comment", skip_serializing_if = "Option::is_none")]
    pub comment: Option<Box<models::Comment>>,
    #[serde(rename = "comment_id", skip_serializing_if = "Option::is_none")]
    pub comment_id: Option<i64>,
    #[serde(rename = "content", skip_serializing_if = "Option::is_none")]
    pub content: Option<String>,
    #[serde(rename = "created", skip_serializing_if = "Option::is_none")]
    pub created: Option<String>,
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<i64>,
    #[serde(rename = "is_private", skip_serializing_if = "Option::is_none")]
    pub is_private: Option<bool>,
    #[serde(rename = "op_type", skip_serializing_if = "Option::is_none")]
    pub op_type: Option<String>,
    #[serde(rename = "ref_name", skip_serializing_if = "Option::is_none")]
    pub ref_name: Option<String>,
    #[serde(rename = "repo", skip_serializing_if = "Option::is_none")]
    pub repo: Option<Box<models::Repository>>,
    #[serde(rename = "repo_id", skip_serializing_if = "Option::is_none")]
    pub repo_id: Option<i64>,
    #[serde(rename = "user_id", skip_serializing_if = "Option::is_none")]
    pub user_id: Option<i64>,
}

impl Activity {
    pub fn new() -> Activity {
        Activity {
            act_user: None,
            act_user_id: None,
            comment: None,
            comment_id: None,
            content: None,
            created: None,
            id: None,
            is_private: None,
            op_type: None,
            ref_name: None,
            repo: None,
            repo_id: None,
            user_id: None,
        }
    }
}
