/*
 * Gitea API
 *
 * This documentation describes the Gitea API.
 *
 * The version of the OpenAPI document: 1.22.0+dev-892-g9de5e39e2
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

/// ActivityPub : ActivityPub type
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ActivityPub {
    #[serde(rename = "@context", skip_serializing_if = "Option::is_none")]
    pub at_context: Option<String>,
}

impl ActivityPub {
    /// ActivityPub type
    pub fn new() -> ActivityPub {
        ActivityPub { at_context: None }
    }
}
