/*
 * Gitea API.
 *
 * This documentation describes the Gitea API.
 *
 * The version of the OpenAPI document: 1.18.0+dev-283-gefaa9958b
 * 
 * Generated by: https://openapi-generator.tech
 */

/// AddTimeOption : AddTimeOption options for adding time to an issue



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct AddTimeOption {
    #[serde(rename = "created", skip_serializing_if = "Option::is_none")]
    pub created: Option<String>,
    /// time in seconds
    #[serde(rename = "time")]
    pub time: i64,
    /// User who spent the time (optional)
    #[serde(rename = "user_name", skip_serializing_if = "Option::is_none")]
    pub user_name: Option<String>,
}

impl AddTimeOption {
    /// AddTimeOption options for adding time to an issue
    pub fn new(time: i64) -> AddTimeOption {
        AddTimeOption {
            created: None,
            time,
            user_name: None,
        }
    }
}


