/*
 * Gitea API.
 *
 * This documentation describes the Gitea API.
 *
 * The version of the OpenAPI document: 1.18.0+dev-283-gefaa9958b
 * 
 * Generated by: https://openapi-generator.tech
 */

/// AddCollaboratorOption : AddCollaboratorOption options when adding a user as a collaborator of a repository



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct AddCollaboratorOption {
    #[serde(rename = "permission", skip_serializing_if = "Option::is_none")]
    pub permission: Option<String>,
}

impl AddCollaboratorOption {
    /// AddCollaboratorOption options when adding a user as a collaborator of a repository
    pub fn new() -> AddCollaboratorOption {
        AddCollaboratorOption {
            permission: None,
        }
    }
}


