/*
 * Gitea API.
 *
 * This documentation describes the Gitea API.
 *
 * The version of the OpenAPI document: 1.18.0+dev-283-gefaa9958b
 * 
 * Generated by: https://openapi-generator.tech
 */

/// AnnotatedTagObject : AnnotatedTagObject contains meta information of the tag object



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct AnnotatedTagObject {
    #[serde(rename = "sha", skip_serializing_if = "Option::is_none")]
    pub sha: Option<String>,
    #[serde(rename = "type", skip_serializing_if = "Option::is_none")]
    pub _type: Option<String>,
    #[serde(rename = "url", skip_serializing_if = "Option::is_none")]
    pub url: Option<String>,
}

impl AnnotatedTagObject {
    /// AnnotatedTagObject contains meta information of the tag object
    pub fn new() -> AnnotatedTagObject {
        AnnotatedTagObject {
            sha: None,
            _type: None,
            url: None,
        }
    }
}


