/*
 * Gitea API
 *
 * This documentation describes the Gitea API.
 *
 * The version of the OpenAPI document: 1.22.0+dev-892-g9de5e39e2
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

/// AnnotatedTagObject : AnnotatedTagObject contains meta information of the tag object
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AnnotatedTagObject {
    #[serde(rename = "sha", skip_serializing_if = "Option::is_none")]
    pub sha: Option<String>,
    #[serde(rename = "type", skip_serializing_if = "Option::is_none")]
    pub r#type: Option<String>,
    #[serde(rename = "url", skip_serializing_if = "Option::is_none")]
    pub url: Option<String>,
}

impl AnnotatedTagObject {
    /// AnnotatedTagObject contains meta information of the tag object
    pub fn new() -> AnnotatedTagObject {
        AnnotatedTagObject {
            sha: None,
            r#type: None,
            url: None,
        }
    }
}
