/*
 * Gitea API
 *
 * This documentation describes the Gitea API.
 *
 * The version of the OpenAPI document: 1.22.0+dev-892-g9de5e39e2
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

/// BadgeList : BadgeList
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct BadgeList {
    /// in:body
    #[serde(rename = "body", skip_serializing_if = "Option::is_none")]
    pub body: Option<Vec<models::Badge>>,
}

impl BadgeList {
    /// BadgeList
    pub fn new() -> BadgeList {
        BadgeList { body: None }
    }
}
