/*
 * Gitea API
 *
 * This documentation describes the Gitea API.
 *
 * The version of the OpenAPI document: 1.22.0+dev-892-g9de5e39e2
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

/// CommitAffectedFiles : CommitAffectedFiles store information about files affected by the commit
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CommitAffectedFiles {
    #[serde(rename = "filename", skip_serializing_if = "Option::is_none")]
    pub filename: Option<String>,
    #[serde(rename = "status", skip_serializing_if = "Option::is_none")]
    pub status: Option<String>,
}

impl CommitAffectedFiles {
    /// CommitAffectedFiles store information about files affected by the commit
    pub fn new() -> CommitAffectedFiles {
        CommitAffectedFiles {
            filename: None,
            status: None,
        }
    }
}
