/*
 * Gitea API.
 *
 * This documentation describes the Gitea API.
 *
 * The version of the OpenAPI document: 1.18.0+dev-283-gefaa9958b
 * 
 * Generated by: https://openapi-generator.tech
 */

/// CreateEmailOption : CreateEmailOption options when creating email addresses



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct CreateEmailOption {
    /// email addresses to add
    #[serde(rename = "emails", skip_serializing_if = "Option::is_none")]
    pub emails: Option<Vec<String>>,
}

impl CreateEmailOption {
    /// CreateEmailOption options when creating email addresses
    pub fn new() -> CreateEmailOption {
        CreateEmailOption {
            emails: None,
        }
    }
}


