/*
 * Gitea API
 *
 * This documentation describes the Gitea API.
 *
 * The version of the OpenAPI document: 1.22.0+dev-892-g9de5e39e2
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

/// CreateLabelOption : CreateLabelOption options for creating a label
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateLabelOption {
    #[serde(rename = "color")]
    pub color: String,
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    #[serde(rename = "exclusive", skip_serializing_if = "Option::is_none")]
    pub exclusive: Option<bool>,
    #[serde(rename = "is_archived", skip_serializing_if = "Option::is_none")]
    pub is_archived: Option<bool>,
    #[serde(rename = "name")]
    pub name: String,
}

impl CreateLabelOption {
    /// CreateLabelOption options for creating a label
    pub fn new(color: String, name: String) -> CreateLabelOption {
        CreateLabelOption {
            color,
            description: None,
            exclusive: None,
            is_archived: None,
            name,
        }
    }
}
