/*
 * Gitea API
 *
 * This documentation describes the Gitea API.
 *
 * The version of the OpenAPI document: 1.22.0+dev-892-g9de5e39e2
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

/// CreateAccessTokenOption : CreateAccessTokenOption options when create access token
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateAccessTokenOption {
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "scopes", skip_serializing_if = "Option::is_none")]
    pub scopes: Option<Vec<String>>,
}

impl CreateAccessTokenOption {
    /// CreateAccessTokenOption options when create access token
    pub fn new(name: String) -> CreateAccessTokenOption {
        CreateAccessTokenOption { name, scopes: None }
    }
}
