/*
 * Gitea API
 *
 * This documentation describes the Gitea API.
 *
 * The version of the OpenAPI document: 1.22.0+dev-892-g9de5e39e2
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

/// CreateEmailOption : CreateEmailOption options when creating email addresses
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateEmailOption {
    /// email addresses to add
    #[serde(rename = "emails", skip_serializing_if = "Option::is_none")]
    pub emails: Option<Vec<String>>,
}

impl CreateEmailOption {
    /// CreateEmailOption options when creating email addresses
    pub fn new() -> CreateEmailOption {
        CreateEmailOption { emails: None }
    }
}
