/*
 * Gitea API.
 *
 * This documentation describes the Gitea API.
 *
 * The version of the OpenAPI document: 1.18.0+dev-283-gefaa9958b
 *
 * Generated by: https://openapi-generator.tech
 */

/// CreateIssueCommentOption : CreateIssueCommentOption options for creating a comment on an issue

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct CreateIssueCommentOption {
    #[serde(rename = "body")]
    pub body: String,
}

impl CreateIssueCommentOption {
    /// CreateIssueCommentOption options for creating a comment on an issue
    pub fn new(body: String) -> CreateIssueCommentOption {
        CreateIssueCommentOption { body }
    }
}
