/*
 * Gitea API.
 *
 * This documentation describes the Gitea API.
 *
 * The version of the OpenAPI document: 1.18.0+dev-283-gefaa9958b
 * 
 * Generated by: https://openapi-generator.tech
 */

/// CreateOAuth2ApplicationOptions : CreateOAuth2ApplicationOptions holds options to create an oauth2 application



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct CreateOAuth2ApplicationOptions {
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(rename = "redirect_uris", skip_serializing_if = "Option::is_none")]
    pub redirect_uris: Option<Vec<String>>,
}

impl CreateOAuth2ApplicationOptions {
    /// CreateOAuth2ApplicationOptions holds options to create an oauth2 application
    pub fn new() -> CreateOAuth2ApplicationOptions {
        CreateOAuth2ApplicationOptions {
            name: None,
            redirect_uris: None,
        }
    }
}


