/*
 * Gitea API
 *
 * This documentation describes the Gitea API.
 *
 * The version of the OpenAPI document: 1.22.0+dev-892-g9de5e39e2
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

/// CreateOrUpdateSecretOption : CreateOrUpdateSecretOption options when creating or updating secret
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateOrUpdateSecretOption {
    /// Data of the secret to update
    #[serde(rename = "data")]
    pub data: String,
}

impl CreateOrUpdateSecretOption {
    /// CreateOrUpdateSecretOption options when creating or updating secret
    pub fn new(data: String) -> CreateOrUpdateSecretOption {
        CreateOrUpdateSecretOption { data }
    }
}
