/*
 * Gitea API
 *
 * This documentation describes the Gitea API.
 *
 * The version of the OpenAPI document: 1.22.0+dev-892-g9de5e39e2
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

/// CreatePullReviewOptions : CreatePullReviewOptions are options to create a pull review
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreatePullReviewOptions {
    #[serde(rename = "body", skip_serializing_if = "Option::is_none")]
    pub body: Option<String>,
    #[serde(rename = "comments", skip_serializing_if = "Option::is_none")]
    pub comments: Option<Vec<models::CreatePullReviewComment>>,
    #[serde(rename = "commit_id", skip_serializing_if = "Option::is_none")]
    pub commit_id: Option<String>,
    /// ReviewStateType review state type
    #[serde(rename = "event", skip_serializing_if = "Option::is_none")]
    pub event: Option<String>,
}

impl CreatePullReviewOptions {
    /// CreatePullReviewOptions are options to create a pull review
    pub fn new() -> CreatePullReviewOptions {
        CreatePullReviewOptions {
            body: None,
            comments: None,
            commit_id: None,
            event: None,
        }
    }
}
