/*
 * Gitea API.
 *
 * This documentation describes the Gitea API.
 *
 * The version of the OpenAPI document: 1.18.0+dev-283-gefaa9958b
 * 
 * Generated by: https://openapi-generator.tech
 */

/// CreateKeyOption : CreateKeyOption options when creating a key



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct CreateKeyOption {
    /// An armored SSH key to add
    #[serde(rename = "key")]
    pub key: String,
    /// Describe if the key has only read access or read/write
    #[serde(rename = "read_only", skip_serializing_if = "Option::is_none")]
    pub read_only: Option<bool>,
    /// Title of the key to add
    #[serde(rename = "title")]
    pub title: String,
}

impl CreateKeyOption {
    /// CreateKeyOption options when creating a key
    pub fn new(key: String, title: String) -> CreateKeyOption {
        CreateKeyOption {
            key,
            read_only: None,
            title,
        }
    }
}


