/*
 * Gitea API.
 *
 * This documentation describes the Gitea API.
 *
 * The version of the OpenAPI document: 1.18.0+dev-283-gefaa9958b
 *
 * Generated by: https://openapi-generator.tech
 */

/// DismissPullReviewOptions : DismissPullReviewOptions are options to dismiss a pull review

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct DismissPullReviewOptions {
    #[serde(rename = "message", skip_serializing_if = "Option::is_none")]
    pub message: Option<String>,
    #[serde(rename = "priors", skip_serializing_if = "Option::is_none")]
    pub priors: Option<bool>,
}

impl DismissPullReviewOptions {
    /// DismissPullReviewOptions are options to dismiss a pull review
    pub fn new() -> DismissPullReviewOptions {
        DismissPullReviewOptions {
            message: None,
            priors: None,
        }
    }
}
