/*
 * Gitea API.
 *
 * This documentation describes the Gitea API.
 *
 * The version of the OpenAPI document: 1.18.0+dev-283-gefaa9958b
 *
 * Generated by: https://openapi-generator.tech
 */

/// EditDeadlineOption : EditDeadlineOption options for creating a deadline

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct EditDeadlineOption {
    #[serde(rename = "due_date")]
    pub due_date: String,
}

impl EditDeadlineOption {
    /// EditDeadlineOption options for creating a deadline
    pub fn new(due_date: String) -> EditDeadlineOption {
        EditDeadlineOption { due_date }
    }
}
