/*
 * Gitea API.
 *
 * This documentation describes the Gitea API.
 *
 * The version of the OpenAPI document: 1.18.0+dev-283-gefaa9958b
 *
 * Generated by: https://openapi-generator.tech
 */

/// EditReactionOption : EditReactionOption contain the reaction type

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct EditReactionOption {
    #[serde(rename = "content", skip_serializing_if = "Option::is_none")]
    pub content: Option<String>,
}

impl EditReactionOption {
    /// EditReactionOption contain the reaction type
    pub fn new() -> EditReactionOption {
        EditReactionOption { content: None }
    }
}
