/*
 * Gitea API
 *
 * This documentation describes the Gitea API.
 *
 * The version of the OpenAPI document: 1.22.0+dev-892-g9de5e39e2
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

/// EditDeadlineOption : EditDeadlineOption options for creating a deadline
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct EditDeadlineOption {
    #[serde(rename = "due_date")]
    pub due_date: String,
}

impl EditDeadlineOption {
    /// EditDeadlineOption options for creating a deadline
    pub fn new(due_date: String) -> EditDeadlineOption {
        EditDeadlineOption { due_date }
    }
}
