/*
 * Gitea API
 *
 * This documentation describes the Gitea API.
 *
 * The version of the OpenAPI document: 1.22.0+dev-892-g9de5e39e2
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

/// EditAttachmentOptions : EditAttachmentOptions options for editing attachments
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct EditAttachmentOptions {
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
}

impl EditAttachmentOptions {
    /// EditAttachmentOptions options for editing attachments
    pub fn new() -> EditAttachmentOptions {
        EditAttachmentOptions { name: None }
    }
}
