/*
 * Gitea API
 *
 * This documentation describes the Gitea API.
 *
 * The version of the OpenAPI document: 1.22.0+dev-892-g9de5e39e2
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

/// EditIssueCommentOption : EditIssueCommentOption options for editing a comment
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct EditIssueCommentOption {
    #[serde(rename = "body")]
    pub body: String,
}

impl EditIssueCommentOption {
    /// EditIssueCommentOption options for editing a comment
    pub fn new(body: String) -> EditIssueCommentOption {
        EditIssueCommentOption { body }
    }
}
