/*
 * Gitea API
 *
 * This documentation describes the Gitea API.
 *
 * The version of the OpenAPI document: 1.22.0+dev-892-g9de5e39e2
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

/// EditGitHookOption : EditGitHookOption options when modifying one Git hook
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct EditGitHookOption {
    #[serde(rename = "content", skip_serializing_if = "Option::is_none")]
    pub content: Option<String>,
}

impl EditGitHookOption {
    /// EditGitHookOption options when modifying one Git hook
    pub fn new() -> EditGitHookOption {
        EditGitHookOption { content: None }
    }
}
