/*
 * Gitea API.
 *
 * This documentation describes the Gitea API.
 *
 * The version of the OpenAPI document: 1.18.0+dev-283-gefaa9958b
 *
 * Generated by: https://openapi-generator.tech
 */

/// EditIssueOption : EditIssueOption options for editing an issue

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct EditIssueOption {
    /// deprecated
    #[serde(rename = "assignee", skip_serializing_if = "Option::is_none")]
    pub assignee: Option<String>,
    #[serde(rename = "assignees", skip_serializing_if = "Option::is_none")]
    pub assignees: Option<Vec<String>>,
    #[serde(rename = "body", skip_serializing_if = "Option::is_none")]
    pub body: Option<String>,
    #[serde(rename = "due_date", skip_serializing_if = "Option::is_none")]
    pub due_date: Option<String>,
    #[serde(rename = "milestone", skip_serializing_if = "Option::is_none")]
    pub milestone: Option<i64>,
    #[serde(rename = "ref", skip_serializing_if = "Option::is_none")]
    pub _ref: Option<String>,
    #[serde(rename = "state", skip_serializing_if = "Option::is_none")]
    pub state: Option<String>,
    #[serde(rename = "title", skip_serializing_if = "Option::is_none")]
    pub title: Option<String>,
    #[serde(rename = "unset_due_date", skip_serializing_if = "Option::is_none")]
    pub unset_due_date: Option<bool>,
}

impl EditIssueOption {
    /// EditIssueOption options for editing an issue
    pub fn new() -> EditIssueOption {
        EditIssueOption {
            assignee: None,
            assignees: None,
            body: None,
            due_date: None,
            milestone: None,
            _ref: None,
            state: None,
            title: None,
            unset_due_date: None,
        }
    }
}
