/*
 * Gitea API
 *
 * This documentation describes the Gitea API.
 *
 * The version of the OpenAPI document: 1.22.0+dev-892-g9de5e39e2
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

/// ExternalWiki : ExternalWiki represents setting for external wiki
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ExternalWiki {
    /// URL of external wiki.
    #[serde(rename = "external_wiki_url", skip_serializing_if = "Option::is_none")]
    pub external_wiki_url: Option<String>,
}

impl ExternalWiki {
    /// ExternalWiki represents setting for external wiki
    pub fn new() -> ExternalWiki {
        ExternalWiki {
            external_wiki_url: None,
        }
    }
}
