/*
 * Gitea API.
 *
 * This documentation describes the Gitea API.
 *
 * The version of the OpenAPI document: 1.18.0+dev-283-gefaa9958b
 *
 * Generated by: https://openapi-generator.tech
 */

/// FileLinksResponse : FileLinksResponse contains the links for a repo's file

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct FileLinksResponse {
    #[serde(rename = "git", skip_serializing_if = "Option::is_none")]
    pub git: Option<String>,
    #[serde(rename = "html", skip_serializing_if = "Option::is_none")]
    pub html: Option<String>,
    #[serde(rename = "self", skip_serializing_if = "Option::is_none")]
    pub _self: Option<String>,
}

impl FileLinksResponse {
    /// FileLinksResponse contains the links for a repo's file
    pub fn new() -> FileLinksResponse {
        FileLinksResponse {
            git: None,
            html: None,
            _self: None,
        }
    }
}
