/*
 * Gitea API
 *
 * This documentation describes the Gitea API.
 *
 * The version of the OpenAPI document: 1.22.0+dev-892-g9de5e39e2
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

/// FileDeleteResponse : FileDeleteResponse contains information about a repo's file that was deleted
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct FileDeleteResponse {
    #[serde(rename = "commit", skip_serializing_if = "Option::is_none")]
    pub commit: Option<Box<models::FileCommitResponse>>,
    #[serde(rename = "content", skip_serializing_if = "Option::is_none")]
    pub content: Option<serde_json::Value>,
    #[serde(rename = "verification", skip_serializing_if = "Option::is_none")]
    pub verification: Option<Box<models::PayloadCommitVerification>>,
}

impl FileDeleteResponse {
    /// FileDeleteResponse contains information about a repo's file that was deleted
    pub fn new() -> FileDeleteResponse {
        FileDeleteResponse {
            commit: None,
            content: None,
            verification: None,
        }
    }
}
