/*
 * Gitea API.
 *
 * This documentation describes the Gitea API.
 *
 * The version of the OpenAPI document: 1.18.0+dev-283-gefaa9958b
 * 
 * Generated by: https://openapi-generator.tech
 */

/// FileDeleteResponse : FileDeleteResponse contains information about a repo's file that was deleted



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct FileDeleteResponse {
    #[serde(rename = "commit", skip_serializing_if = "Option::is_none")]
    pub commit: Option<Box<crate::models::FileCommitResponse>>,
    #[serde(rename = "content", skip_serializing_if = "Option::is_none")]
    pub content: Option<serde_json::Value>,
    #[serde(rename = "verification", skip_serializing_if = "Option::is_none")]
    pub verification: Option<Box<crate::models::PayloadCommitVerification>>,
}

impl FileDeleteResponse {
    /// FileDeleteResponse contains information about a repo's file that was deleted
    pub fn new() -> FileDeleteResponse {
        FileDeleteResponse {
            commit: None,
            content: None,
            verification: None,
        }
    }
}


