/*
 * Gitea API.
 *
 * This documentation describes the Gitea API.
 *
 * The version of the OpenAPI document: 1.18.0+dev-283-gefaa9958b
 *
 * Generated by: https://openapi-generator.tech
 */

/// FileResponse : FileResponse contains information about a repo's file

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct FileResponse {
    #[serde(rename = "commit", skip_serializing_if = "Option::is_none")]
    pub commit: Option<Box<crate::models::FileCommitResponse>>,
    #[serde(rename = "content", skip_serializing_if = "Option::is_none")]
    pub content: Option<Box<crate::models::ContentsResponse>>,
    #[serde(rename = "verification", skip_serializing_if = "Option::is_none")]
    pub verification: Option<Box<crate::models::PayloadCommitVerification>>,
}

impl FileResponse {
    /// FileResponse contains information about a repo's file
    pub fn new() -> FileResponse {
        FileResponse {
            commit: None,
            content: None,
            verification: None,
        }
    }
}
