/*
 * Gitea API
 *
 * This documentation describes the Gitea API.
 *
 * The version of the OpenAPI document: 1.22.0+dev-892-g9de5e39e2
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

/// FileLinksResponse : FileLinksResponse contains the links for a repo's file
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct FileLinksResponse {
    #[serde(rename = "git", skip_serializing_if = "Option::is_none")]
    pub git: Option<String>,
    #[serde(rename = "html", skip_serializing_if = "Option::is_none")]
    pub html: Option<String>,
    #[serde(rename = "self", skip_serializing_if = "Option::is_none")]
    pub param_self: Option<String>,
}

impl FileLinksResponse {
    /// FileLinksResponse contains the links for a repo's file
    pub fn new() -> FileLinksResponse {
        FileLinksResponse {
            git: None,
            html: None,
            param_self: None,
        }
    }
}
