/*
 * Gitea API
 *
 * This documentation describes the Gitea API.
 *
 * The version of the OpenAPI document: 1.22.0+dev-892-g9de5e39e2
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

/// GeneralAttachmentSettings : GeneralAttachmentSettings contains global Attachment settings exposed by API
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GeneralAttachmentSettings {
    #[serde(rename = "allowed_types", skip_serializing_if = "Option::is_none")]
    pub allowed_types: Option<String>,
    #[serde(rename = "enabled", skip_serializing_if = "Option::is_none")]
    pub enabled: Option<bool>,
    #[serde(rename = "max_files", skip_serializing_if = "Option::is_none")]
    pub max_files: Option<i64>,
    #[serde(rename = "max_size", skip_serializing_if = "Option::is_none")]
    pub max_size: Option<i64>,
}

impl GeneralAttachmentSettings {
    /// GeneralAttachmentSettings contains global Attachment settings exposed by API
    pub fn new() -> GeneralAttachmentSettings {
        GeneralAttachmentSettings {
            allowed_types: None,
            enabled: None,
            max_files: None,
            max_size: None,
        }
    }
}
