/*
 * Gitea API
 *
 * This documentation describes the Gitea API.
 *
 * The version of the OpenAPI document: 1.22.0+dev-892-g9de5e39e2
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

/// GeneralApiSettings : GeneralAPISettings contains global api settings exposed by it
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GeneralApiSettings {
    #[serde(
        rename = "default_git_trees_per_page",
        skip_serializing_if = "Option::is_none"
    )]
    pub default_git_trees_per_page: Option<i64>,
    #[serde(
        rename = "default_max_blob_size",
        skip_serializing_if = "Option::is_none"
    )]
    pub default_max_blob_size: Option<i64>,
    #[serde(rename = "default_paging_num", skip_serializing_if = "Option::is_none")]
    pub default_paging_num: Option<i64>,
    #[serde(rename = "max_response_items", skip_serializing_if = "Option::is_none")]
    pub max_response_items: Option<i64>,
}

impl GeneralApiSettings {
    /// GeneralAPISettings contains global api settings exposed by it
    pub fn new() -> GeneralApiSettings {
        GeneralApiSettings {
            default_git_trees_per_page: None,
            default_max_blob_size: None,
            default_paging_num: None,
            max_response_items: None,
        }
    }
}
