/*
 * Gitea API.
 *
 * This documentation describes the Gitea API.
 *
 * The version of the OpenAPI document: 1.18.0+dev-283-gefaa9958b
 *
 * Generated by: https://openapi-generator.tech
 */

/// GpgKeyEmail : GPGKeyEmail an email attached to a GPGKey

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct GpgKeyEmail {
    #[serde(rename = "email", skip_serializing_if = "Option::is_none")]
    pub email: Option<String>,
    #[serde(rename = "verified", skip_serializing_if = "Option::is_none")]
    pub verified: Option<bool>,
}

impl GpgKeyEmail {
    /// GPGKeyEmail an email attached to a GPGKey
    pub fn new() -> GpgKeyEmail {
        GpgKeyEmail {
            email: None,
            verified: None,
        }
    }
}
