/*
 * Gitea API
 *
 * This documentation describes the Gitea API.
 *
 * The version of the OpenAPI document: 1.22.0+dev-892-g9de5e39e2
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

/// LicensesTemplateListEntry : LicensesListEntry is used for the API
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct LicensesTemplateListEntry {
    #[serde(rename = "key", skip_serializing_if = "Option::is_none")]
    pub key: Option<String>,
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(rename = "url", skip_serializing_if = "Option::is_none")]
    pub url: Option<String>,
}

impl LicensesTemplateListEntry {
    /// LicensesListEntry is used for the API
    pub fn new() -> LicensesTemplateListEntry {
        LicensesTemplateListEntry {
            key: None,
            name: None,
            url: None,
        }
    }
}
