/*
 * Gitea API.
 *
 * This documentation describes the Gitea API.
 *
 * The version of the OpenAPI document: 1.18.0+dev-283-gefaa9958b
 *
 * Generated by: https://openapi-generator.tech
 */

/// NotificationCount : NotificationCount number of unread notifications

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct NotificationCount {
    #[serde(rename = "new", skip_serializing_if = "Option::is_none")]
    pub new: Option<i64>,
}

impl NotificationCount {
    /// NotificationCount number of unread notifications
    pub fn new() -> NotificationCount {
        NotificationCount { new: None }
    }
}
