/*
 * Gitea API
 *
 * This documentation describes the Gitea API.
 *
 * The version of the OpenAPI document: 1.22.0+dev-892-g9de5e39e2
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

/// NotificationCount : NotificationCount number of unread notifications
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct NotificationCount {
    #[serde(rename = "new", skip_serializing_if = "Option::is_none")]
    pub new: Option<i64>,
}

impl NotificationCount {
    /// NotificationCount number of unread notifications
    pub fn new() -> NotificationCount {
        NotificationCount { new: None }
    }
}
