/*
 * Gitea API
 *
 * This documentation describes the Gitea API.
 *
 * The version of the OpenAPI document: 1.22.0+dev-892-g9de5e39e2
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

/// Permission : Permission represents a set of permissions
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Permission {
    #[serde(rename = "admin", skip_serializing_if = "Option::is_none")]
    pub admin: Option<bool>,
    #[serde(rename = "pull", skip_serializing_if = "Option::is_none")]
    pub pull: Option<bool>,
    #[serde(rename = "push", skip_serializing_if = "Option::is_none")]
    pub push: Option<bool>,
}

impl Permission {
    /// Permission represents a set of permissions
    pub fn new() -> Permission {
        Permission {
            admin: None,
            pull: None,
            push: None,
        }
    }
}
