/*
 * Gitea API
 *
 * This documentation describes the Gitea API.
 *
 * The version of the OpenAPI document: 1.22.0+dev-892-g9de5e39e2
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

/// PullReviewRequestOptions : PullReviewRequestOptions are options to add or remove pull review requests
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PullReviewRequestOptions {
    #[serde(rename = "reviewers", skip_serializing_if = "Option::is_none")]
    pub reviewers: Option<Vec<String>>,
    #[serde(rename = "team_reviewers", skip_serializing_if = "Option::is_none")]
    pub team_reviewers: Option<Vec<String>>,
}

impl PullReviewRequestOptions {
    /// PullReviewRequestOptions are options to add or remove pull review requests
    pub fn new() -> PullReviewRequestOptions {
        PullReviewRequestOptions {
            reviewers: None,
            team_reviewers: None,
        }
    }
}
