/*
 * Gitea API
 *
 * This documentation describes the Gitea API.
 *
 * The version of the OpenAPI document: 1.22.0+dev-892-g9de5e39e2
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

/// PushMirror : PushMirror represents information of a push mirror
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PushMirror {
    #[serde(rename = "created", skip_serializing_if = "Option::is_none")]
    pub created: Option<String>,
    #[serde(rename = "interval", skip_serializing_if = "Option::is_none")]
    pub interval: Option<String>,
    #[serde(rename = "last_error", skip_serializing_if = "Option::is_none")]
    pub last_error: Option<String>,
    #[serde(rename = "last_update", skip_serializing_if = "Option::is_none")]
    pub last_update: Option<String>,
    #[serde(rename = "remote_address", skip_serializing_if = "Option::is_none")]
    pub remote_address: Option<String>,
    #[serde(rename = "remote_name", skip_serializing_if = "Option::is_none")]
    pub remote_name: Option<String>,
    #[serde(rename = "repo_name", skip_serializing_if = "Option::is_none")]
    pub repo_name: Option<String>,
    #[serde(rename = "sync_on_commit", skip_serializing_if = "Option::is_none")]
    pub sync_on_commit: Option<bool>,
}

impl PushMirror {
    /// PushMirror represents information of a push mirror
    pub fn new() -> PushMirror {
        PushMirror {
            created: None,
            interval: None,
            last_error: None,
            last_update: None,
            remote_address: None,
            remote_name: None,
            repo_name: None,
            sync_on_commit: None,
        }
    }
}
