/*
 * Gitea API
 *
 * This documentation describes the Gitea API.
 *
 * The version of the OpenAPI document: 1.22.0+dev-892-g9de5e39e2
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

/// RenameUserOption : RenameUserOption options when renaming a user
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct RenameUserOption {
    /// New username for this user. This name cannot be in use yet by any other user.
    #[serde(rename = "new_username")]
    pub new_username: String,
}

impl RenameUserOption {
    /// RenameUserOption options when renaming a user
    pub fn new(new_username: String) -> RenameUserOption {
        RenameUserOption { new_username }
    }
}
