/*
 * Gitea API.
 *
 * This documentation describes the Gitea API.
 *
 * The version of the OpenAPI document: 1.18.0+dev-283-gefaa9958b
 * 
 * Generated by: https://openapi-generator.tech
 */

/// RepoTransfer : RepoTransfer represents a pending repo transfer



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct RepoTransfer {
    #[serde(rename = "doer", skip_serializing_if = "Option::is_none")]
    pub doer: Option<Box<crate::models::User>>,
    #[serde(rename = "recipient", skip_serializing_if = "Option::is_none")]
    pub recipient: Option<Box<crate::models::User>>,
    #[serde(rename = "teams", skip_serializing_if = "Option::is_none")]
    pub teams: Option<Vec<crate::models::Team>>,
}

impl RepoTransfer {
    /// RepoTransfer represents a pending repo transfer
    pub fn new() -> RepoTransfer {
        RepoTransfer {
            doer: None,
            recipient: None,
            teams: None,
        }
    }
}


