/*
 * Gitea API.
 *
 * This documentation describes the Gitea API.
 *
 * The version of the OpenAPI document: 1.18.0+dev-283-gefaa9958b
 *
 * Generated by: https://openapi-generator.tech
 */

/// RepositoryMeta : RepositoryMeta basic repository information

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct RepositoryMeta {
    #[serde(rename = "full_name", skip_serializing_if = "Option::is_none")]
    pub full_name: Option<String>,
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<i64>,
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(rename = "owner", skip_serializing_if = "Option::is_none")]
    pub owner: Option<String>,
}

impl RepositoryMeta {
    /// RepositoryMeta basic repository information
    pub fn new() -> RepositoryMeta {
        RepositoryMeta {
            full_name: None,
            id: None,
            name: None,
            owner: None,
        }
    }
}
