/*
 * Gitea API.
 *
 * This documentation describes the Gitea API.
 *
 * The version of the OpenAPI document: 1.18.0+dev-283-gefaa9958b
 *
 * Generated by: https://openapi-generator.tech
 */

/// ServerVersion : ServerVersion wraps the version of the server

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ServerVersion {
    #[serde(rename = "version", skip_serializing_if = "Option::is_none")]
    pub version: Option<String>,
}

impl ServerVersion {
    /// ServerVersion wraps the version of the server
    pub fn new() -> ServerVersion {
        ServerVersion { version: None }
    }
}
