/*
 * Gitea API.
 *
 * This documentation describes the Gitea API.
 *
 * The version of the OpenAPI document: 1.18.0+dev-283-gefaa9958b
 * 
 * Generated by: https://openapi-generator.tech
 */

/// SubmitPullReviewOptions : SubmitPullReviewOptions are options to submit a pending pull review



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct SubmitPullReviewOptions {
    #[serde(rename = "body", skip_serializing_if = "Option::is_none")]
    pub body: Option<String>,
    /// ReviewStateType review state type
    #[serde(rename = "event", skip_serializing_if = "Option::is_none")]
    pub event: Option<String>,
}

impl SubmitPullReviewOptions {
    /// SubmitPullReviewOptions are options to submit a pending pull review
    pub fn new() -> SubmitPullReviewOptions {
        SubmitPullReviewOptions {
            body: None,
            event: None,
        }
    }
}


