/*
 * Gitea API.
 *
 * This documentation describes the Gitea API.
 *
 * The version of the OpenAPI document: 1.18.0+dev-283-gefaa9958b
 * 
 * Generated by: https://openapi-generator.tech
 */

/// TopicName : TopicName a list of repo topic names



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct TopicName {
    #[serde(rename = "topics", skip_serializing_if = "Option::is_none")]
    pub topics: Option<Vec<String>>,
}

impl TopicName {
    /// TopicName a list of repo topic names
    pub fn new() -> TopicName {
        TopicName {
            topics: None,
        }
    }
}


