/*
 * Gitea API
 *
 * This documentation describes the Gitea API.
 *
 * The version of the OpenAPI document: 1.22.0+dev-892-g9de5e39e2
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

/// UpdateUserAvatarOption : UpdateUserAvatarUserOption options when updating the user avatar
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UpdateUserAvatarOption {
    /// image must be base64 encoded
    #[serde(rename = "image", skip_serializing_if = "Option::is_none")]
    pub image: Option<String>,
}

impl UpdateUserAvatarOption {
    /// UpdateUserAvatarUserOption options when updating the user avatar
    pub fn new() -> UpdateUserAvatarOption {
        UpdateUserAvatarOption { image: None }
    }
}
