/*
 * Gitea API
 *
 * This documentation describes the Gitea API.
 *
 * The version of the OpenAPI document: 1.22.0+dev-892-g9de5e39e2
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

/// UserBadgeOption : UserBadgeOption options for link between users and badges
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UserBadgeOption {
    #[serde(rename = "badge_slugs", skip_serializing_if = "Option::is_none")]
    pub badge_slugs: Option<Vec<String>>,
}

impl UserBadgeOption {
    /// UserBadgeOption options for link between users and badges
    pub fn new() -> UserBadgeOption {
        UserBadgeOption { badge_slugs: None }
    }
}
