/*
 * Gitea API
 *
 * This documentation describes the Gitea API.
 *
 * The version of the OpenAPI document: 1.22.0+dev-892-g9de5e39e2
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

/// UserHeatmapData : UserHeatmapData represents the data needed to create a heatmap
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UserHeatmapData {
    #[serde(rename = "contributions", skip_serializing_if = "Option::is_none")]
    pub contributions: Option<i64>,
    /// TimeStamp defines a timestamp
    #[serde(rename = "timestamp", skip_serializing_if = "Option::is_none")]
    pub timestamp: Option<i64>,
}

impl UserHeatmapData {
    /// UserHeatmapData represents the data needed to create a heatmap
    pub fn new() -> UserHeatmapData {
        UserHeatmapData {
            contributions: None,
            timestamp: None,
        }
    }
}
