/*
 * Gitea API.
 *
 * This documentation describes the Gitea API.
 *
 * The version of the OpenAPI document: 1.18.0+dev-283-gefaa9958b
 *
 * Generated by: https://openapi-generator.tech
 */

/// WikiCommitList : WikiCommitList commit/revision list

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct WikiCommitList {
    #[serde(rename = "commits", skip_serializing_if = "Option::is_none")]
    pub commits: Option<Vec<crate::models::WikiCommit>>,
    #[serde(rename = "count", skip_serializing_if = "Option::is_none")]
    pub count: Option<i64>,
}

impl WikiCommitList {
    /// WikiCommitList commit/revision list
    pub fn new() -> WikiCommitList {
        WikiCommitList {
            commits: None,
            count: None,
        }
    }
}
