/*
 * Gitea API.
 *
 * This documentation describes the Gitea API.
 *
 * The version of the OpenAPI document: 1.18.0+dev-283-gefaa9958b
 *
 * Generated by: https://openapi-generator.tech
 */

/// WikiCommit : WikiCommit page commit/revision

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct WikiCommit {
    #[serde(rename = "author", skip_serializing_if = "Option::is_none")]
    pub author: Option<Box<crate::models::CommitUser>>,
    #[serde(rename = "commiter", skip_serializing_if = "Option::is_none")]
    pub commiter: Option<Box<crate::models::CommitUser>>,
    #[serde(rename = "message", skip_serializing_if = "Option::is_none")]
    pub message: Option<String>,
    #[serde(rename = "sha", skip_serializing_if = "Option::is_none")]
    pub sha: Option<String>,
}

impl WikiCommit {
    /// WikiCommit page commit/revision
    pub fn new() -> WikiCommit {
        WikiCommit {
            author: None,
            commiter: None,
            message: None,
            sha: None,
        }
    }
}
